base_url                = "https://tfr.davidguerrero.fr"                  # Terraform registry base URL
repository_url          = "https://github.com/Heldroe/terraform-modules/" # Git forge repository URL
html                    = true
gzip                    = true
terraform_docs          = true
invalidation_file       = "invalidations.txt"
invalidation_format     = "txt"
invalidation_full_url   = true
invalidation_url_encode = true
invalidation_dirs       = true
html_base               = ".tfr-static/base.html"
