name: Publish all modules

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      # Registry variables
      BASE_URL: "https://tfr.davidguerrero.fr"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-tags: "true"

      - name: Setup tfr-static
        uses: ./.github/actions/setup-tfr-static

      - name: Generate static registry
        run: |
          # TODO: set params as HCL config rather than CLI params
          tfr-static publish \
            --all \
            --base-url "$BASE_URL" \
            --terraform-docs \
            --gzip \
            --html \
            --html-base .tfr-static/base.html

      - name: Upload static registry
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ENDPOINT_URL_S3: ${{ secrets.AWS_ENDPOINT_URL_S3 }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        run: |
          # Pass 1: Sync ONLY modules archives (.tar.gz) and delete orphaned archives
          aws s3 sync \
            target/ s3://$BUCKET_NAME/ \
            --exclude "*" \
            --include "*.tar.gz" \
            --content-type application/gzip \
            --delete

          # Pass 2: Sync everything EXCEPT archives and delete orphaned non-archive files
          aws s3 sync \
            target/ s3://$BUCKET_NAME/ \
            --exclude "*.tar.gz" \
            --content-encoding gzip \
            --delete

      - name: Full CDN Cache Purge
        env:
          BUNNYNET_API_KEY: ${{ secrets.BUNNYNET_API_KEY }}
          BUNNYNET_PULL_ZONE_ID: ${{ secrets.BUNNYNET_PULL_ZONE_ID }}
        run: |
          echo "Triggering full cache purge for pull zone: $BUNNYNET_PULL_ZONE_ID"

          curl --request POST \
            --url "https://api.bunny.net/pullzone/$BUNNYNET_PULL_ZONE_ID/purgeCache" \
            --header "AccessKey: $BUNNYNET_API_KEY" \
            --header "Accept: application/json" \
            --silent --show-error --fail

          echo -e "\nPurge triggered successfully."
